adapter: postgresql
encoding: unicode
database: hurum_db
username: postgres_hurum
password: 'password'
host: localhost

# если у вас не настроен postgresql
# adapter: sqlite3
# database: lib/db/development.sqlite3
